/**
 * Memo presentation + export (DR-3e) — pure so the panel stays declarative and the Markdown
 * export is unit-testable. The memo is the deliverable: a recommendation, a thesis, and findings
 * that each carry an evidence chain back to shared, provenance-tagged memory.
 */

import type { Memo, Recommendation } from "./agents/synthesis";

export interface RecommendationMeta {
  label: string;
  /** CSS tone token (globals.css): ok = green, warn = amber, down = red. */
  tone: "ok" | "warn" | "down";
}

export const RECOMMENDATION: Record<Recommendation, RecommendationMeta> = {
  proceed: { label: "Proceed", tone: "ok" },
  proceed_with_conditions: { label: "Proceed with conditions", tone: "warn" },
  pass: { label: "Pass", tone: "down" },
};

/** Counts of risks vs strengths in a memo. */
export function findingTally(memo: Memo): { risks: number; strengths: number } {
  let risks = 0;
  let strengths = 0;
  for (const f of memo.findings) {
    if (f.kind === "risk") risks += 1;
    else strengths += 1;
  }
  return { risks, strengths };
}

/** The memo as a downloadable Markdown document. */
export function memoToMarkdown(memo: Memo): string {
  const rec = RECOMMENDATION[memo.recommendation];
  const { risks, strengths } = findingTally(memo);
  const lines: string[] = [
    `# Investment Memo — ${memo.target}`,
    "",
    `**Recommendation:** ${rec.label}`,
    `**Findings:** ${risks} risk${risks === 1 ? "" : "s"}, ${strengths} strength${strengths === 1 ? "" : "s"}`,
    "",
    "## Thesis",
    "",
    memo.thesis,
  ];

  const section = (title: string, kind: "risk" | "strength") => {
    const items = memo.findings.filter((f) => f.kind === kind);
    if (items.length === 0) return;
    lines.push("", `## ${title}`);
    for (const f of items) {
      lines.push("", `### ${f.title} _(confidence ${Math.round(f.confidence * 100)}%)_`, "", f.detail);
      if (f.evidence.length > 0) {
        lines.push("", "Evidence:");
        for (const e of f.evidence) lines.push(`- ${e}`);
      }
    }
  };
  section("Risks", "risk");
  section("Strengths", "strength");

  lines.push("", "---", "_Generated by The Due-Diligence Room · arango-agentic-memory (shared, provenance-tagged memory)._");
  return lines.join("\n");
}

/** Filename for the exported memo, e.g. "memo-northwind-robotics.md". */
export function memoFilename(memo: Memo): string {
  const slug = memo.target.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "");
  return `memo-${slug || "target"}.md`;
}
